import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Pinyon_Script, Ephesis } from 'next/font/google'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Load Pinyon Script font
const pinyonScript = Pinyon_Script({
  weight: "400", // Only available in weight 400
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pinyon-script",
});

// Load Ephesis font
const ephesis = Ephesis({
  weight: "400", // Only available in weight 400
  subsets: ["latin"],
  display: "swap",
  variable: "--font-ephesis",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ephesis.variable} ${pinyonScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
